### PR TITLE
Fix React api link and overall member names for non Blazor components not correctly opening.

### LINKED ISSUE #1025: React api links not working
Currently the React api link point to wrongly built URL that contains and extra `_grids` in it.

For example try opening any of the links in:
https://staging.infragistics.com/products/ignite-ui-react/react/components/grids/grid/advanced-filtering#api-references

### LINKED ISSUE #1026: Api links for member names do not scroll the page to said member
This is only for WebComponents and React. For Blazor seems to be ok.

Try opening any of the member links in:
https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/menus/toolbar#tool-actions

For example `overlayId` opens:
https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igniteui_webcomponents_layouts.igctoolactioncomponent.html#overlayid

This does not scroll the page linked to the `overlayId` member because the casing in this case matters and the URL should end with `#overlayId` instead.

### PR DESCRIPTION
**Pull request by skrustev**
Resolves #1025
Resolves #1026

### CODE REVIEW

File: src/ext/MarkdownTransformer.ts [hunk 1]
```diff
@@ -130,7 +130,8 @@ function getApiLink(apiRoot: string, typeName: string, memberName: string | null
             let packageText = "";
             if (packageName) {
                 if (packageName == "igniteui-webgrids") {
-                    packageText = "igniteui_" + getPlatformName(<APIPlatform>options.platform).toLowerCase() + "_grids_grids."
+                    const packageSuffix = (platform == APIPlatform.React ? "" : "_grids") + "_grids.";
```
Comment (mddragnev) [inline src/ext/MarkdownTransformer.ts:133]: Might be a better idea to use the strict equality. Anyway it is good

**Review by mddragnev — APPROVED** [review]
